# 应用名称
spring:
  application:
    name: eureka-grpc-server
server:
  port: 8772
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false

grpc:
  server:
    port: 0